// 曲データと型定義

export type SkillLevel = "◎" | "○" | "△" | "×";

export type Song = {
  id: number;
  title: string;
  titleKana: string;
  artist: string;
  artistKana: string;
  genre: string;
  scale: string;
  instUrl: string; // 空文字 or URL
  skillLevel: SkillLevel;
  isPublic: boolean;
  createdAt: string;
};

// 曲データ本体
export const songs: Song[] = [
  {
    id: 1,
    title: "スターライトパレード",
    titleKana: "すたーらいとぱれーど",
    artist: "SEKAI NO OWARI",
    artistKana: "せかいのおわり",
    genre: "J-POP",
    scale: "Bm",
    instUrl: "https://youtu.be/cdALVVc-dv8",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 2,
    title: "千本桜",
    titleKana: "せんぼんざくら",
    artist: "黒うさP",
    artistKana: "くろうさぴー",
    genre: "ボカロ",
    scale: "Fm → Gm",
    instUrl: "https://youtu.be/1WuakCHtbVU",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 3,
    title: "心做し",
    titleKana: "こころなし",
    artist: "蝶々P",
    artistKana: "ちょうちょうぴー",
    genre: "ボカロ",
    scale: "Bm",
    instUrl: "https://youtu.be/bo8HVKTzIkw",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 4,
    title: "シャルル",
    titleKana: "しゃるる",
    artist: "バルーン",
    artistKana: "ばるーん",
    genre: "ボカロ",
    scale: "Gm",
    instUrl: "https://youtu.be/3tqikIDPGoM",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 5,
    title: "ダーリン",
    titleKana: "だーりん",
    artist: "須田景凪",
    artistKana: "すだけいな",
    genre: "J-POP",
    scale: "Fm（＋1転調）",
    instUrl: "https://youtu.be/uIFlcRerYFY",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 6,
    title: "ファンサ",
    titleKana: "ふぁんさ",
    artist: "HoneyWorks",
    artistKana: "はにーわーくす",
    genre: "J-POP",
    scale: "Em",
    instUrl: "https://youtu.be/mKQQeLQkARg",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 7,
    title: "ルーム No.4",
    titleKana: "るーむなんばーふぉー",
    artist: "超学生",
    artistKana: "ちょうがくせい",
    genre: "J-POP",
    scale: "C♯m",
    instUrl: "https://youtu.be/nonG76Et4ak",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 8,
    title: "ギラギラ",
    titleKana: "ぎらぎら",
    artist: "Ado",
    artistKana: "あど",
    genre: "J-POP",
    scale: "D → F",
    instUrl: "https://youtu.be/qKvDNzS9niE",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 9,
    title: "アスノヨゾラ哨戒班",
    titleKana: "あすのよぞらしょうかいはん",
    artist: "Orangestar",
    artistKana: "おれんじすたー",
    genre: "ボカロ",
    scale: "F♯m",
    instUrl: "https://youtu.be/XGuWGoj5wNw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 10,
    title: "フォニィ",
    titleKana: "ふぉにぃ",
    artist: "ツミキ",
    artistKana: "つみき",
    genre: "ボカロ",
    scale: "Am",
    instUrl: "https://youtu.be/JOsLjuQ6_bI",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 11,
    title: "レディメイド",
    titleKana: "れでぃめいど",
    artist: "Ado",
    artistKana: "あど",
    genre: "J-POP",
    scale: "Fm",
    instUrl: "https://youtu.be/gqUXFVQE7II",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 12,
    title: "踊",
    titleKana: "おど",
    artist: "Ado",
    artistKana: "あど",
    genre: "J-POP",
    scale: "Fm",
    instUrl: "https://youtu.be/O7uDs1tw2TE",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 13,
    title: "ラヴィ",
    titleKana: "らゔぃ",
    artist: "すりぃ",
    artistKana: "すりぃ",
    genre: "ボカロ",
    scale: "G♯m",
    instUrl: "https://youtu.be/f4vShdWZlMY",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 14,
    title: "酔いどれ知らず",
    titleKana: "よいどれしらず",
    artist: "Kanaria",
    artistKana: "かなりあ",
    genre: "ボカロ",
    scale: "F♯m",
    instUrl: "https://youtu.be/vBykSwT3QXw",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 15,
    title: "私は最強",
    titleKana: "わたしはさいきょう",
    artist: "Ado",
    artistKana: "あど",
    genre: "J-POP",
    scale: "E",
    instUrl: "https://youtu.be/i85TRObs9FY",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 16,
    title: "ラブカ？",
    titleKana: "らぶか",
    artist: "柊キライ",
    artistKana: "ひいらぎきらい",
    genre: "ボカロ",
    scale: "F",
    instUrl: "https://youtu.be/aZ_tQcqbDYg",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 17,
    title: "病名は愛だった",
    titleKana: "びょうめいはあいだった",
    artist: "Neru",
    artistKana: "ねる",
    genre: "ボカロ",
    scale: "Bm",
    instUrl: "https://youtu.be/uSmjfR74tiY",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 18,
    title: "吉原ラメント",
    titleKana: "よしわららめんと",
    artist: "亜沙",
    artistKana: "あさ",
    genre: "ボカロ",
    scale: "A♯m → Bm",
    instUrl: "https://youtu.be/1jXa7BO7D_4",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 19,
    title: "ヴァンパイア",
    titleKana: "ゔぁんぱいあ",
    artist: "DECO*27",
    artistKana: "でこにーな",
    genre: "ボカロ",
    scale: "C♯m",
    instUrl: "https://youtu.be/QmcaGLGMvm0",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 20,
    title: "真生活",
    titleKana: "しんせいかつ",
    artist: "案山子",
    artistKana: "かかし",
    genre: "ボカロ",
    scale: "C♯",
    instUrl: "https://youtu.be/ggiyE4ZMtrQ",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 21,
    title: "Black Out",
    titleKana: "ぶらっく あうと",
    artist: "nijiPMario",
    artistKana: "にじぴーまりお",
    genre: "ボカロ",
    scale: "Cm",
    instUrl: "https://youtu.be/QTHBhVOFTdc",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 22,
    title: "フレンズ",
    titleKana: "ふれんず",
    artist: "REBECCA",
    artistKana: "れべっか",
    genre: "懐メロ",
    scale: "G",
    instUrl: "https://youtu.be/UHfm28TH8Yo",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 23,
    title: "未来予想図Ⅱ",
    titleKana: "みらいよそうず に",
    artist: "DREAMS COME TRUE",
    artistKana: "どりーむず かむ とぅるー",
    genre: "J-POP",
    scale: "C♯",
    instUrl: "https://youtu.be/yQQmerloOs0",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 24,
    title: "ハレンチ",
    titleKana: "はれんち",
    artist: "ちゃんみな",
    artistKana: "ちゃんみな",
    genre: "J-POP",
    scale: "Bm → F♯m",
    instUrl: "https://youtu.be/q9nGEuEK8TY",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 25,
    title: "君をのせて",
    titleKana: "きみをのせて",
    artist: "井上あずみ",
    artistKana: "いのうえあずみ",
    genre: "ジブリ",
    scale: "F♯",
    instUrl: "https://youtu.be/dD2U2RRAHMQ",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 26,
    title: "ねぇねぇねぇ。",
    titleKana: "ねぇねぇねぇ",
    artist: "ピノキオピー",
    artistKana: "ぴのきおぴー",
    genre: "ボカロ",
    scale: "G",
    instUrl: "https://youtu.be/MBWCHu5LPFw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 27,
    title: "ヤミタイガール",
    titleKana: "やみたいがーる",
    artist: "れるりり",
    artistKana: "れるりり",
    genre: "ボカロ",
    scale: "F♯m",
    instUrl: "https://youtu.be/Mv09KYTTbK0",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 28,
    title: "CH4NGE",
    titleKana: "ちぇんじ",
    artist: "Giga",
    artistKana: "ぎが",
    genre: "ボカロ",
    scale: "C♯",
    instUrl: "https://youtu.be/2kOP6KG6xxc",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 29,
    title: "ロミオとシンデレラ",
    titleKana: "ろみおとしんでれら",
    artist: "doriko",
    artistKana: "どりこ",
    genre: "ボカロ",
    scale: "F♯",
    instUrl: "https://youtu.be/ZtNefULpCFw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 30,
    title: "オラはにんきもの",
    titleKana: "おらはにんきもの",
    artist: "矢島晶子",
    artistKana: "やじまあきこ",
    genre: "アニソン",
    scale: "C",
    instUrl: "https://youtu.be/F7wPTvQR0Tc",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 31,
    title: "Beyond the way",
    titleKana: "びよんど ざ うぇい",
    artist: "Giga",
    artistKana: "ぎが",
    genre: "ボカロ",
    scale: "G♯m",
    instUrl: "https://youtu.be/OfWM_C748tQ",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 32,
    title: "ニア",
    titleKana: "にあ",
    artist: "夏代孝明",
    artistKana: "なつしろたかあき",
    genre: "ボカロ",
    scale: "F♯ → A",
    instUrl: "https://youtu.be/koFH6Bhj4PY",
    skillLevel: "△",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 33,
    title: "夜もすがら君想ふ",
    titleKana: "よもすがらきみおもう",
    artist: "TOKOTOKO（西沢さんP）",
    artistKana: "とことこ にしざわさんぴー",
    genre: "ボカロ",
    scale: "Cm → Dm",
    instUrl: "https://youtu.be/YkOh3AmApwo",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 34,
    title: "ロメオ",
    titleKana: "ろめお",
    artist: "HoneyWorks",
    artistKana: "はにーわーくす",
    genre: "J-POP",
    scale: "D♯（＋3想定）",
    instUrl: "https://youtu.be/-qOT1xI5_BM",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 35,
    title: "チューリングラブ",
    titleKana: "ちゅーりんぐらぶ",
    artist: "ナナヲアカリ",
    artistKana: "ななおあかり",
    genre: "J-POP",
    scale: "Am",
    instUrl: "https://youtu.be/j-8L5KFC3ms",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 36,
    title: "Shadow Shadow",
    titleKana: "しゃどう しゃどう",
    artist: "Azari",
    artistKana: "あざり",
    genre: "ボカロ",
    scale: "B",
    instUrl: "https://youtu.be/CAQG6enUYB4",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 37,
    title: "G4L",
    titleKana: "ぎゃる",
    artist: "Giga",
    artistKana: "ぎが",
    genre: "ボカロ",
    scale: "E",
    instUrl: "https://youtu.be/4YhOS67BFY0",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 38,
    title: "ラヴィット",
    titleKana: "らゔぃっと",
    artist: "ピノキオピー",
    artistKana: "ぴのきおぴー",
    genre: "ボカロ",
    scale: "E",
    instUrl: "https://youtu.be/mzd6ESlIsoM",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 39,
    title: "絶頂讃歌",
    titleKana: "ぜっちょうさんか",
    artist: "和ぬか",
    artistKana: "わぬか",
    genre: "J-POP",
    scale: "G♯",
    instUrl: "https://youtu.be/YxMisLpPnUs",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 40,
    title: "ダーリンダンス",
    titleKana: "だーりんだんす",
    artist: "かいりきベア",
    artistKana: "かいりきべあ",
    genre: "ボカロ",
    scale: "E → F",
    instUrl: "https://youtu.be/0iW9pVQSwwI",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 41,
    title: "カゲロウデイズ",
    titleKana: "かげろうでいず",
    artist: "じん（自然の敵P）",
    artistKana: "じん しぜんのてきぴー",
    genre: "ボカロ",
    scale: "Em → F♯m → Gm",
    instUrl: "https://youtu.be/i_sgLCLURtE",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 42,
    title: "フライデー・ナイト",
    titleKana: "ふらいでー・ないと",
    artist: "なとり",
    artistKana: "なとり",
    genre: "J-POP",
    scale: "D♯",
    instUrl: "https://youtu.be/aMOEj8aHjn4",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 43,
    title: "ビリビリ",
    titleKana: "びりびり",
    artist: "すりぃ",
    artistKana: "すりぃ",
    genre: "ボカロ",
    scale: "F♯m",
    instUrl: "https://youtu.be/VpYZssxWgbw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 44,
    title: "シャンティ",
    titleKana: "しゃんてぃ",
    artist: "wotaku",
    artistKana: "うぉたく",
    genre: "ボカロ",
    scale: "A（→ A♯）",
    instUrl: "https://youtu.be/1_XhK8OAPrs",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 45,
    title: "アンノウン・マザーグース",
    titleKana: "あんのうん・まざーぐーす",
    artist: "wowaka",
    artistKana: "をわか",
    genre: "ボカロ",
    scale: "A",
    instUrl: "https://youtu.be/tb95fTqEKEI?si=IMfXb5Y7NPCq3FF0",
    skillLevel: "△",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 46,
    title: "ARROW",
    titleKana: "あろー",
    artist: "niki",
    artistKana: "にき",
    genre: "ボカロ",
    scale: "G",
    instUrl: "https://youtu.be/0KKCWDVyquE?si=YRhx12HJ_l9lIXNS",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 47,
    title: "天ノ弱",
    titleKana: "あまのじゃく",
    artist: "164",
    artistKana: "いちろくよん",
    genre: "ボカロ",
    scale: "A → A♯",
    instUrl: "https://youtu.be/lEhIkyX4oAI?si=PqFqB53t64kFPM9K",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 48,
    title: "あなたの夜が明けるまで",
    titleKana: "あなたのよるがあけるまで",
    artist: "傘村トータ",
    artistKana: "かさむらとーた",
    genre: "ボカロ",
    scale: "G → G♯ → A",
    instUrl: "https://youtu.be/gJm94mMtDBs?si=aYN2NunL2JdYH4Cw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 49,
    title: "アイデンティティ",
    titleKana: "あいでんてぃてぃ",
    artist: "Kanaria",
    artistKana: "かなりあ",
    genre: "ボカロ",
    scale: "Gm",
    instUrl: "https://youtu.be/87BoGnFVekM?si=J2zzNG7l0-ALB0nW",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 50,
    title: "EYE",
    titleKana: "あい",
    artist: "Kanaria",
    artistKana: "かなりあ",
    genre: "ボカロ",
    scale: "A",
    instUrl: "https://youtu.be/lDX8mWOwdok?si=sWBc84o9wW5jhfII",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 51,
    title: "unravel",
    titleKana: "あんらべる",
    artist: "TK from 凛として時雨",
    artistKana: "てぃーけー ふろむ りんとしてしぐれ",
    genre: "アニソン",
    scale: "Gm",
    instUrl: "https://youtu.be/JLKo8qOv-G8?si=rnVFiUdGVPGuMwZw",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 52,
    title: "いーあるふぁんくらぶ",
    titleKana: "いーあるふぁんくらぶ",
    artist: "みきとP",
    artistKana: "みきとぴー",
    genre: "ボカロ",
    scale: "A♯",
    instUrl: "https://youtu.be/OCisc4uojLY?si=Usa1uAWFWt0CIfNC",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 53,
    title: "命に嫌われている。",
    titleKana: "いのちにきらわれている",
    artist: "カンザキイオリ",
    artistKana: "かんざきいおり",
    genre: "ボカロ",
    scale: "C",
    instUrl: "https://youtu.be/-X3Blew9fWY?si=k6LCli9MWoS7FkAT",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 54,
    title: "ヴィラン",
    titleKana: "ゔぃらん",
    artist: "てにをは",
    artistKana: "てにをは",
    genre: "ボカロ",
    scale: "Em",
    instUrl: "https://youtu.be/mKShosKaUB8?si=kx4Kiv9Tq4jrMLkA",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 55,
    title: "炎上アリス",
    titleKana: "えんじょうありす",
    artist: "かいりきベア",
    artistKana: "かいりきべあ",
    genre: "ボカロ",
    scale: "C♯（A♯m）",
    instUrl: "https://youtu.be/pftVXIcW6e8?si=fxEwHuAdLIY2va6y",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 56,
    title: "Casino",
    titleKana: "かじの",
    artist: "Azari",
    artistKana: "あざり",
    genre: "ボカロ",
    scale: "G → G♯",
    instUrl: "https://youtu.be/fjNOTSErKPk?si=PK0AXOn3CV74qAV9",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 57,
    title: "神っぽいな",
    titleKana: "かみっぽいな",
    artist: "ピノキオピー",
    artistKana: "ぴのきおぴー",
    genre: "ボカロ",
    scale: "F",
    instUrl: "https://youtu.be/cNNhPDTSiMU?si=2Zs-7EP1jJR-OXE6",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 58,
    title: "KING",
    titleKana: "きんぐ",
    artist: "Kanaria",
    artistKana: "かなりあ",
    genre: "ボカロ",
    scale: "D♯ → F",
    instUrl: "https://youtu.be/wrS7_VmDS3Y?si=f_4hxao3P-fUjVqS",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 59,
    title: "QUEEN",
    titleKana: "くいーん",
    artist: "Kanaria",
    artistKana: "かなりあ",
    genre: "ボカロ",
    scale: "D♯",
    instUrl: "https://youtu.be/zXTvm5Kbn5U?si=wcTGmCkzNXmrQFQM",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 60,
    title: "ゴーストルール",
    titleKana: "ごーすとるーる",
    artist: "DECO*27",
    artistKana: "でこにーな",
    genre: "ボカロ",
    scale: "A",
    instUrl: "https://youtu.be/BcyuGkm14ns?si=5XFEWS1dcwwqZ2_B",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 61,
    title: "猿芝居",
    titleKana: "さるしばい",
    artist: "なとり",
    artistKana: "なとり",
    genre: "ボカロ",
    scale: "C",
    instUrl: "https://youtu.be/6yU8eSXvxro?si=NZO5e7Kq5tDcePMW",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 62,
    title: "残響散歌",
    titleKana: "ざんきょうさんか",
    artist: "Aimer",
    artistKana: "えめ",
    genre: "アニソン",
    scale: "B",
    instUrl: "https://youtu.be/8NN-9L97upk?si=rHuh60HOgbLUAOlc",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 63,
    title: "懺悔参り",
    titleKana: "ざんげまいり",
    artist: "羽生まゐご",
    artistKana: "はにゅうまいご",
    genre: "ボカロ",
    scale: "D",
    instUrl: "https://youtu.be/agn8-dNPVDs",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 64,
    title: "心象カスケード",
    titleKana: "しんしょうかすけーど",
    artist: "電ポルP",
    artistKana: "でんぽるぴー",
    genre: "ボカロ",
    scale: "G",
    instUrl: "https://youtu.be/o8zqvbtOpvM",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 65,
    title: "少女レイ",
    titleKana: "しょうじょれい",
    artist: "みきとP",
    artistKana: "みきとぴー",
    genre: "ボカロ",
    scale: "A / A♯",
    instUrl: "https://youtu.be/XLa2e_VG9fE",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 66,
    title: "食虫植物",
    titleKana: "しょくちゅうしょくぶつ",
    artist: "理芽",
    artistKana: "りめ",
    genre: "ボカロ",
    scale: "F♯",
    instUrl: "https://youtu.be/RSys9VWVgHs",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 67,
    title: "snooze",
    titleKana: "すぬーず",
    artist: "wotaku",
    artistKana: "うぉたく",
    genre: "ボカロ",
    scale: "Em / G",
    instUrl: "https://youtu.be/Rb463TodXJA",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 68,
    title: "snow jam",
    titleKana: "すのーじゃむ",
    artist: "Rin音",
    artistKana: "りんね",
    genre: "J-POP",
    scale: "A♯m",
    instUrl: "https://youtu.be/Gw1URK_JOxs",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 69,
    title: "ダウナーウィッチ",
    titleKana: "だうなーうぃっち",
    artist: "ツミキ",
    artistKana: "つみき",
    genre: "ボカロ",
    scale: "Em",
    instUrl: "https://youtu.be/S5e-AkdTJJs",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 70,
    title: "絶え間なく藍色",
    titleKana: "たえまなくあいいろ",
    artist: "獅子志司",
    artistKana: "しししし",
    genre: "ボカロ",
    scale: "D♯",
    instUrl: "https://youtu.be/Nyy4Tk0Ldzk",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 71,
    title: "テレキャスタービーボーイ",
    titleKana: "てれきゃすたーびーぼーい",
    artist: "すりぃ",
    artistKana: "すりぃ",
    genre: "ボカロ",
    scale: "C♯",
    instUrl: "https://youtu.be/mCVRpoMsCl8",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 72,
    title: "とても素敵な六月でした",
    titleKana: "とてもすてきなろくがつでした",
    artist: "Eight",
    artistKana: "えいと",
    genre: "ボカロ",
    scale: "C♯",
    instUrl: "https://youtu.be/HujWpOq2_vM",
    skillLevel: "△",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 73,
    title: "DOGMA",
    titleKana: "どぐま",
    artist: "wotaku",
    artistKana: "うぉたく",
    genre: "ボカロ",
    scale: "D♯",
    instUrl: "https://youtu.be/88hJ8VVilSE",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 74,
    title: "曇天",
    titleKana: "どんてん",
    artist: "DOES",
    artistKana: "だず",
    genre: "アニソン",
    scale: "F",
    instUrl: "https://youtu.be/fONHd-lNStw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 75,
    title: "ベノム",
    titleKana: "べのむ",
    artist: "かいりきベア",
    artistKana: "かいりきべあ",
    genre: "ボカロ",
    scale: "F♯ → G♯",
    instUrl: "https://youtu.be/duvJFyF3fGI",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 76,
    title: "バットオンリーユー",
    titleKana: "ばっとおんりーゆー",
    artist: "syudou",
    artistKana: "しゅどう",
    genre: "ボカロ",
    scale: "B",
    instUrl: "https://youtu.be/rgYB-Fu7pUw",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 77,
    title: "ビーバー",
    titleKana: "びーばー",
    artist: "すりぃ",
    artistKana: "すりぃ",
    genre: "ボカロ",
    scale: "Gm → Fm",
    instUrl: "https://youtu.be/PgCNxf1VXJY",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 78,
    title: "ヒバナ",
    titleKana: "ひばな",
    artist: "DECO*27",
    artistKana: "でこにーな",
    genre: "ボカロ",
    scale: "F♯ → A → A♯",
    instUrl: "https://youtu.be/I9ioBZOoNpI",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 79,
    title: "flos",
    titleKana: "ふろす",
    artist: "R Sound Design",
    artistKana: "あーるさうんどでざいん",
    genre: "ボカロ",
    scale: "E",
    instUrl: "https://youtu.be/ATPYL9B7PZ8",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 80,
    title: "ブリキノダンス",
    titleKana: "ぶりきのだんす",
    artist: "日向電工",
    artistKana: "ひなたでんこう",
    genre: "ボカロ",
    scale: "F",
    instUrl: "https://youtu.be/aTrYJ6Sm_BY",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 81,
    title: "MACARON",
    titleKana: "まかろん",
    artist: "ATOLS",
    artistKana: "あとるす",
    genre: "ボカロ",
    scale: "C♯",
    instUrl: "https://youtu.be/XF6vflhAEFc",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 82,
    title: "妄想感傷代償連盟",
    titleKana: "もうそうかんしょうだいしょうれんめい",
    artist: "DECO*27",
    artistKana: "でこにーな",
    genre: "ボカロ",
    scale: "D♯",
    instUrl: "https://youtu.be/wpuR5406fjk",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 83,
    title: "夜明けと蛍",
    titleKana: "よあけとほたる",
    artist: "n-buna",
    artistKana: "なぶな",
    genre: "ボカロ",
    scale: "G → G♯（Em → Fm）",
    instUrl: "https://youtu.be/GI46AChYcfU",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 84,
    title: "余薫",
    titleKana: "よくん",
    artist: "いよわ",
    artistKana: "いよわ",
    genre: "ボカロ",
    scale: "A → A♯",
    instUrl: "https://youtu.be/GbJdXzSmjB0",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 85,
    title: "ロウワー",
    titleKana: "ろうわー",
    artist: "ぬゆり",
    artistKana: "ぬゆり",
    genre: "ボカロ",
    scale: "A → G♯ → A",
    instUrl: "https://youtu.be/koUTtmJAXgg",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 86,
    title: "ロキ",
    titleKana: "ろき",
    artist: "みきとP",
    artistKana: "みきとぴー",
    genre: "ボカロ",
    scale: "Bm",
    instUrl: "https://youtu.be/USvUTkIFvIY",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 87,
    title: "THAW",
    titleKana: "そう",
    artist: "Amnesia",
    artistKana: "あむねしあ",
    genre: "K-POP",
    scale: "E → D♯",
    instUrl: "https://youtu.be/7gae49B49mo?si=ICbo3SvtThpIG9he",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 88,
    title: "金曜日のおはよう",
    titleKana: "きんようびのおはよう",
    artist: "HoneyWorks",
    artistKana: "はにーわーくす",
    genre: "ボカロ",
    scale: "Cm",
    instUrl: "https://youtu.be/CN7CHLrZvgg?si=lZoq3cLdY-XkeS-Z",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 89,
    title: "カブトムシ",
    titleKana: "かぶとむし",
    artist: "aiko",
    artistKana: "あいこ",
    genre: "J-POP",
    scale: "Cm",
    instUrl: "https://youtu.be/ZxB_947qWQk?si=UlyvQMlOBFVgU7dR",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 90,
    title: "残酷な天使のテーゼ",
    titleKana: "ざんこくなてんしのてーぜ",
    artist: "高橋洋子",
    artistKana: "たかはしようこ",
    genre: "アニソン",
    scale: "Cm",
    instUrl: "https://youtu.be/6Wa0l84xm7w?si=FYpUICoDXPDk_CG-",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 91,
    title: "小悪魔だってかまわない！",
    titleKana: "こあくまだってかまわない",
    artist: "めいちゃん",
    artistKana: "めいちゃん",
    genre: "J-POP",
    scale: "G",
    instUrl: "https://youtu.be/0kttMW3IvtM?si=RxQIUKAeu4FQDxlZ",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 92,
    title: "シル・ヴ・プレジデント",
    titleKana: "しる・ゔ・ぷれじでんと",
    artist: "P丸様。",
    artistKana: "ぴーまるさま",
    genre: "ボカロ",
    scale: "F♯m",
    instUrl: "https://youtu.be/l2l8bVcCqA8?si=U-u0QMTGnfJW1aXE",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-12",
  },
  {
    id: 93,
    title: "丸の内サディスティック",
    titleKana: "まるのうちさでぃすてぃっく",
    artist: "椎名林檎",
    artistKana: "しいなりんご",
    genre: "J-POP",
    scale: "不明",
    instUrl: "https://youtu.be/CpYGWhqerSI?si=ZfdPqVxK5l9eYSN9",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-19",
  },
  {
    id: 94,
    title: "そばかす",
    titleKana: "そばかす",
    artist: "JUDY AND MARY",
    artistKana: "じゅでぃあんどまりー",
    genre: "アニソン",
    scale: "不明",
    instUrl: "https://youtu.be/2B9ca54z9Vo?si=fic2f5wv7kTXG3ZV",
    skillLevel: "○",
    isPublic: true,
    createdAt: "2026-02-24",
  },
  {
    id: 95,
    title: "にじいろ",
    titleKana: "にじいろ",
    artist: "綾香",
    artistKana: "あやか",
    genre: "J-POP",
    scale: "不明",
    instUrl: "https://youtu.be/R7_hR2C1l4A?si=lckOkOKCgq2lJXcq",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-24",
  },
  {
    id: 96,
    title: "生まれてはじめて",
    titleKana: "うまれてはじめて",
    artist: "アナと雪の女王",
    artistKana: "あなとゆきのじょうおう",
    genre: "アニソン",
    scale: "不明",
    instUrl: "https://youtu.be/O3xpEoW_uao?si=fVyVPOcDGXYdTRUq",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-24",
  },
  {
    id: 97,
    title: "雪だるまつくろう",
    titleKana: "ゆきだるまつくろう",
    artist: "アナと雪の女王",
    artistKana: "あなとゆきのじょうおう",
    genre: "アニソン",
    scale: "不明",
    instUrl: "https://youtu.be/_byyQ75YQco?si=Wb9qNKFKMBCzb0w5",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-24",
  },
  {
    id: 98,
    title: "ひまわりの約束",
    titleKana: "ひまわりのやくそく",
    artist: "秦基博",
    artistKana: "はたもとひろ",
    genre: "J-POP",
    scale: "不明",
    instUrl: "https://youtu.be/F95NNJ44cNA?si=8UzXJifgOP2uk1sG",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-24",
  },
  {
    id: 99,
    title: "Be…",
    titleKana: "びー",
    artist: "Ms.OOJA",
    artistKana: "みすおーじゃ",
    genre: "J-POP",
    scale: "不明",
    instUrl: "https://youtu.be/kLNBmJjBj78?si=QemUn9anx0UgwdlH",
    skillLevel: "△",
    isPublic: true,
    createdAt: "2026-02-25",
  },
  {
    id: 100,
    title: "手紙 ー拝啓 十五の君へー",
    titleKana: "てがみ",
    artist: "アンジェラ・アキ",
    artistKana: "あんじぇらあき",
    genre: "J-POP",
    scale: "不明",
    instUrl: "https://youtu.be/od6gY25vTpE?si=1VHH-1tceNGo6hMq",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-25",
  },
  {
    id: 101,
    title: "からくりピエロ",
    titleKana: "からくりぴえろ",
    artist: "40mP",
    artistKana: "40めーとるぴー",
    genre: "ボカロ",
    scale: "不明",
    instUrl: "https://youtu.be/Q3_yota1Olc?si=Ng0JXyPaODTKi3MB",
    skillLevel: "◎",
    isPublic: true,
    createdAt: "2026-02-25",
  },
  // ★ここにどんどん追加していく（titleKana / artistKana / scale / genre / playCount 必須）
];